language: r
sudo: true
cache: packages
os:
  - linux
dist:
  - trusty
r:
  - release

before_install:
  - sudo apt-get -qq update

github_packages:
  - covr

after_success:
  - R --slave --vanilla -e 'library(covr); pc <- package_coverage(); pc; codecov(coverage = pc)'
