language: r
cache: packages
r:
  - release

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
